### ISSUE TITLE
Add window variable to set the service name

### ISSUE THREAD

**Issue by Blightwidow** [census-instrumentation/opencensus-web#155]
**Is your feature request related to a problem? Please describe.**
The `startTracing()` method is simple and just needs a few `window` variables. The only issue is that it doesn't allow you to setup a service name for the exporter.

**Describe the solution you'd like**
Add a `window.ocServiceName` optionnal variable.

**Describe alternatives you've considered**
The only alternative I found would be to maybe pass a config object to the `startTracing` method

**Additional context**
Would be willing to open a PR if approved

**Comment by draffensperger** [comment]
I have actually had this idea as well. Your PR would be much welcome! cc/ @crdgonzalezca

**Comment by draffensperger** [comment]
Fixed by #157
