### ISSUE TITLE
B3 propagation on the web

### ISSUE THREAD

**Issue by edvinasbartkus** [census-instrumentation/opencensus-web#171]
Right now, xhr interceptors (in web-instrumentation-zone-peer-deep) use web-propagatation-tracecontext. Wouldn't it make sense that it would be possible to pass through the options what propagation format should be used?

I have a need to setup b3 propagation on the frontend/web and pass it to the backend services and would like to have an option to use b3 propagation with opencensus-web.

I am willing to make a PR with package `opencensus-web-propagation-b3` and make it possible to `startTracing` with `options = {propagation: oc-web-propagatation-tracecontext || opencensus-web-propagation-b3}` if only it makes sense to have such capability.

**Comment by edvinasbartkus** [comment]
Opened PR with the suggested implementation: https://github.com/census-instrumentation/opencensus-web/pull/173

Let me know if that's the right approach.

**Comment by draffensperger** [comment]
This has been released in version `0.0.7` of the library, marking as fixed.

**Comment by edvinasbartkus** [comment]
Thanks!
