### ISSUE TITLE
span.ts does not update startTime and endTime

### ISSUE THREAD

**Issue by jindal93** [census-instrumentation/opencensus-web#36]
span.ts has the following code
```
/** Starts span by setting `startTime` to now. */
  start() {
    this.startPerfTime = performance.now();
  }

  /** Ends the span by setting `endTime` to now. */
  end() {
    this.endPerfTime = performance.now();
  }
```

It just updates the `startPerfTime` and `endPerfTime`. It should ideally update the `startTime` and `endTime` of a span too

**Comment by draffensperger** [comment]
Good question. The Span implementation in OpenCensus Web uses `startPerfTime` and `endPerfTime` as the underlying values, but also provides property getters for [startTime](https://github.com/census-instrumentation/opencensus-web/blob/5cb6119723334f7898e5ab21076052e79f8fc3f1/packages/opencensus-web-core/src/trace/model/span.ts#L101) and [endTime](https://github.com/census-instrumentation/opencensus-web/blob/5cb6119723334f7898e5ab21076052e79f8fc3f1/packages/opencensus-web-core/src/trace/model/span.ts#L116) that calculate their results based on `startPerfTime` and `endPerfTime`.

This behavior is verified in the [test-span.ts](https://github.com/census-instrumentation/opencensus-web/blob/5c151a80a9e93f698fce3ef71841be1eeaff6102/packages/opencensus-web-core/test/test-span.ts#L46) file.

Does this make sense?

**Comment by jindal93** [comment]
Yes. Thanks @draffensperger :)
