### ISSUE TITLE
opencensus web packages in npm registry

### ISSUE THREAD

**Issue by jindal93** [census-instrumentation/opencensus-web#63]
When is the plan to publish opencensus web packages to npm registry?

**Comment by draffensperger** [comment]
Good timing on the question! I just created https://github.com/census-instrumentation/opencensus-web/pull/64 that sets up the release docs and tooling. Once that is in I can propose a release and get it approved and published.

**Comment by draffensperger** [comment]
This is done now! The packages are on npm at version 0.0.1. I'm planning to update the docs with more info for how to use them from NPM, but the release is out.
